bash commands and access patterns for dynamodb

diff --git a/backend-flask/bin/db/db-setup b/backend-flask/bin/db/db-setup
--- a/backend-flask/bin/db/db-setup
+++ b/backend-flask/bin/db/db-setup
@@ -1,7 +1,7 @@
 #! /usr/bin/bash
--e # stop if it fails at any point
+set -e # stop if it fails at any point
 
-bin_path="$(realpath .)/bin"
+bin_path="$(realpath .)/bin/db"
 
 if [[ "$1" == "prod" ]]; then
     PROD_FLAG="prod"
